export const BACKEND = 'http://localhost:3001'

//actions types
export const GET_BREEDS = 'GET_BREEDS'
export const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS'
export const GET_BREEDS_BY_QUERY = 'GET_BREEDS_BY_QUERY'
export const GET_BREEDS_BY_ID = 'GET_BREEDS_BY_ID'
export const DOG_ORDER_BY_AZ = 'DOG_ORDER_BY_AZ'
export const DOG_FILTER_BY_ORIGIN = 'DOG_FILTER_BY_ORIGIN'
export const DOG_FILTER_BY_TEMPERAMENT = 'DOG_FILTER_BY_TEMPERAMENT'
export const DOG_ORDER_BY_WEIGHT = 'DOG_ORDER_BY_WEIGHT'